### PR TITLE
os independent path handling

### PR DESCRIPTION
**Pull request by TarasKuzyo**
added support for unix OS

### CODE REVIEW

**Comment by bazzilic** [comment]
Have you tested that it works on *nix OSes?

**Comment by TarasKuzyo** [comment]
Yes, but I have issues with checksum calculations on linux.

**Comment by TarasKuzyo** [comment]
I've found an issue with bibtex -- it exits with error when there are no citations in tex file.

**Comment by bazzilic** [comment]
Thank you for your contribution. I will review your changes and get back to you. But in general, PRs that rewrite like 70% of the code is not a good idea.

As of now I see certain possible issues with your code.
- IIRC, XeLaTeX and XeTeX output PDF files, at least in the MiKTeX distribution for Windows.
- JPG is a lossy compression, so comparing directly to JPG files might result in `False` even if files are identical (in theory). PNG would have been a better choice.
- `burst_jpeg` procedure assumes that the system has ghostscript installed, which is rarely true for Windows machines
- Lines 299–303 is dangerous code. I see your intention to not force the user to copy the source in the first place, but the implementation of this intention is dangerous. What the script should do instead is request the OS for a temporary folder, copy everything there, and work over there.
- There's something strange with the code formatting, lots of empty lines in seemingly random places
- Some changes you propose are unclear to me. E.g., why was the `substitute_line_in_file` procedure rewritten?

**Pull request closed without merging**
